### ISSUE TITLE
House 5: elevator broken

### ISSUE THREAD

**Issue by dburleson** [CybertownRevival/ctr#1]
Use of the elevator in house 5 drops you out of the house no matter if you use it from the top floor or from the basement and you continue to fall.

Sgeo: That's caused by gravity. X_ITE gravity acts even during animated viewpoints (although I want to double check recent release notes). Blaxxun 4.4 does not. However, Blaxxun 5.x, if I recall correctly, does the same thing

**Comment by nucleare** [comment]
It may or may not be worth noting to add that when you take the elevator from the basement back up, it does bring you back up quite a ways (but not all the way back up) to the top floor before you're accelerated out the direction of where the doors would be. That is to say, I tried walking in backwards to see if it would at least reach the top floor before being spat out to fall through the world and it does not seem so. 
Perhaps it might help to consider changing the mechanics to use a similar function as the one used when right-clicking and selecting a viewpoint whereas the waypoint would have multiple connections to emulate riding the elevator up and down? _Please excuse my lack of coding knowledge in trying to be more helpful to this issue._

**Comment by dburleson** [comment]
potentially fixed home (thanks to GenNormo)

**Comment by dburleson** [comment]
[Home2.wrl.zip](https://github.com/CybertownRevival/ctr/files/10942580/Home2.wrl.zip)

Potentially fixed home by GenNormo (to be confirmed)

**Comment by Sgeo** [comment]
Fix using Browser.setGravity().

This uses the bxx_auth.js shim, as that function was available in Blaxxun Contact but not in the standard. There is no standard equivalent, and X_ITE's functionality for this seems to change from version to version.

00a appears to have used Browser.setGravity while in Cybertown.

[home.wrl.zip](https://github.com/CybertownRevival/ctr/files/10947992/home.wrl.zip)
