### ISSUE TITLE
Login is not case sensitive

### ISSUE THREAD

**Issue by TheMikeSanto** [CybertownRevival/ctr#100]
A user with the username `User1` is able to log in as `uSeR1`, and the system will accept it. Their name will be displayed as such throughout their session. Usernames should be case sensitive.

**Comment by dburleson** [comment]
To clarify, once authenticated, the session should used the username casing stored in the database, not the casing the user has typed to login.

If the database has "MyUsername" stored in the record, and the user logins using "myusername", the session should use "MyUsername" throughout the UI.
