### ISSUE TITLE
Select a home afterwards

### ISSUE THREAD

**Issue by CymNet** [CybertownRevival/ctr#165]
I moved into Cybertown, I selected an empty spot, but I clicked too quickly and forgot to select an image for my house first. So now my spot in Cybertown is an empty green square, no house displayed. How can I select a house afterwards, so my house is visible on the map?

**Comment by theyapps** [comment]
1. Click ![image](https://user-images.githubusercontent.com/15441/222962252-0f7e788e-4d05-452d-ac32-008e0141b36b.png) on the right panel.
2. Click 
![image](https://user-images.githubusercontent.com/15441/222962241-2fa24811-f0bc-4716-a2f8-fdb2dcd58b51.png).
3. Click 
![image](https://user-images.githubusercontent.com/15441/222962288-fc5cee4c-1cf9-4b4b-b619-563b30595df9.png)

Should be able to update from here.
