### ISSUE TITLE
Message board "manage" code sometimes not present

### ISSUE THREAD

**Issue by KovenCT** [CybertownRevival/ctr#186]
When updating the code in the "manage" tab in my home message board, if I refresh the message board and then click manage again, sometimes the code that I inputed isn't present. The text box is entirely blank.

The effect of the code still shows (in my case, an overly large photo of Vin Diesel). However, if I then click update after refreshing, with no code visible, it will then "actually" remove it, so-to-speak. So the image disappears completely.

I hope I've explained it appropriately.

EDIT: This issue seems to be happening more frequently. In fact, sometimes the only way to get the code to show up is to click "post", then cancel, then click "manage", at which point the code shows up. Otherwise, refreshing doesn't seem to resolve it, and in fact the code is "invisible" from the outset, and not just after refreshing the message board.

**Comment by smile0711** [comment]
Fixed with Message Board Bug Squisher
