### ISSUE TITLE
free spaces blocked by homes

### ISSUE THREAD

**Issue by Talaskian** [CybertownRevival/ctr#193]
In Adventure Colony, Imagination Hood, Fantasy Block, there are 2 free spaces being blocked by a home.  making it unable to uncheck the box where a free space is located on update map of the block.  Talaskian CL Adventure Colony

**Comment by smile0711** [comment]
![Block Wizard Bug](https://github.com/CybertownRevival/ctr/assets/98184756/7829c6bd-7d08-47c3-87f5-9da4de59b179)

**Comment by smile0711** [comment]
Fixed by pull request #203
