### ISSUE TITLE
Choose primary role

### ISSUE THREAD

**Issue by dburleson** [CybertownRevival/ctr#202]
Users should be able to select their primary role from the roles they have. This option is available through their profile.

Task requirements

* When a user is give a role, if they don't already have a primary role, assign it as their primary role.
* Provide a drop down in their Profile settings to select the primary role from their current active roles.
* Cron: The role cron should only acknowledge the primary role for the user to give out xp/cc weekly.
* If a user is removed from a role, check if it's their primary role, if it is, assign the next role with the most xp, then cc.

Bonus:
* Show the primary role label in chat, next to their name.

**Comment by smile0711** [comment]
The original did not depend on the primary role due to the fact that some people wanted to display their honory title (elder, Templar, etc.). These titles did not pay more than most jobs, so the cron has to be able to pick highest.
