### ISSUE TITLE
hi! clicking on the information button on the sidebar in the plaza, does not in fact give you information.

### ISSUE THREAD

**Issue by Rhlp-Engineering** [CybertownRevival/ctr#311]
![info button issue](https://github.com/user-attachments/assets/b0dac07f-5897-4011-be8f-2d20fa98b6f2)

**Comment by smile0711** [comment]
Information button is meant to show who the leader of that place is.  The plaza will not have someone, and that button will disappear from that place as we update.

**Comment by Rhlp-Engineering** [comment]
ah cool! thanks!
