### ISSUE TITLE
sprinting , then opeining a menu can result in you having the same speed as before, but your not sprinting.

### ISSUE THREAD

**Issue by Rhlp-Engineering** [CybertownRevival/ctr#312]
https://github.com/user-attachments/assets/817106a1-5479-474d-8c3b-02b53d866ae1

sorry, im over a data connection so the file had to be really small! 2mb ish

basically, you can sometimes retain the speed from sprinting for no reason,
mainly whenever your in a lob by, and then disconnect and reconnect your wifi roughter
or sompthing like that
hope this is at all helpfull and not too confusing
okaibye

**Comment by smile0711** [comment]
Different worlds have a different speed multiplier, so changing worlds maybe just that.  As far as getting shift to be stuck is an acceptable quark of 3d worlds, so fixing for a weird quark is not needed.

**Comment by Rhlp-Engineering** [comment]
speed seems to stack from world to world
