### ISSUE TITLE
some extra small things that arent exactly perfect

### ISSUE THREAD

**Issue by Rhlp-Engineering** [CybertownRevival/ctr#313]
okai my video wont work and im about to pass out so here we go

theres no collision in the bank

the elevators in the mall have a lot of issues, and it's impossible to get to floor 2

nothings for sale in the antique store, and the stuff that is, you cnt buy

almost nothing has a placeholder version

the pool has a lot of collision issues

ok sleep time
hopefully this is usefull
bye!!!!

**Comment by smile0711** [comment]
1. Collision is working in bank when I tested
2. Mall elevators is a known bug
3. Birthstone Clock Apr is currently for sale, it does cost 100cc, so maybe you don't have enough city cash for it
4. Can you DM me about what you mean by place holder version?
5. The pool was riddled with collision issues in original cybertown.

**Comment by Rhlp-Engineering** [comment]
alright I'm sorry I'm reporting the same things again

**Comment by Rhlp-Engineering** [comment]
and by placeholder version, I meant menus or buttons with nothing on them don't have a work in progress padge
