### ISSUE TITLE
Plaza: List of colonies doesn't work

### ISSUE THREAD

**Issue by dburleson** [CybertownRevival/ctr#5]
From matthewS

 The list of colonies changes the world to one that doesn't exist and goes black with a failed to load error.

![002](https://user-images.githubusercontent.com/45258503/149997777-8bed599b-ed17-4772-adb0-a09c23eef306.png)

**Comment by theyapps** [comment]
I have begun looking at this, I have it so it loads the colony. It still opens a blank tab I will correct that and get a pull request submitted.

**Comment by theyapps** [comment]
https://github.com/CybertownRevival/ctr/pull/112

**Comment by theyapps** [comment]
@dburleson This issue can close now that the PR has been accepted.
