### ISSUE TITLE
Neighborhood Page Level

### ISSUE THREAD

**Issue by dburleson** [CybertownRevival/ctr#72]
Create a page to display the hood level.

* [ ] Clickable Map (see archive repo)
* [ ] Message Board / Inbox
* [ ] Map management (saved in the DB)

Issue to be expanded with supporting material (screenshots, templates, etc)

We feel there should be an JavaScript object which will hold theming details for the colony, hoods and blocks to reference for map images and icons.

**Comment by troydotnz** [comment]
Neighborhood level data

[neighbour.sql.txt](https://github.com/CybertownRevival/ctr/files/8649950/neighbour.sql.txt)

**Comment by dburleson** [comment]
testing github webhook

**Comment by dburleson** [comment]
Rough transcript of discussion from me on discord regarding hoods/blocks

```
yeah, so hoods have their own vue component, a record in place and an association record to relate to the colony. The vue component will draw in the chat component too.

Hoods had chat, Blocks didn't


* should have endpoints for fetching hoods related places (ie: /hood/1)
* include a 'place.type' to help define hood/block/colony/public/etc


----------

so, I guess migration would just:

1) select the id of the ent col
2) insert hoods into place 
3) get hood ids
4) insert into association table the ids of the above. relating them to the ent col's id



----------------


I've been thinking about it, and i'm not sure if I like the idea of filling place (or even home) with placeholder records. Therefore, I think a seperate table for managing the block/hood/colony grid is a better idea. It'll be smaller and would be fine for placeholder records:
map_location:
* parent_place_id - the id of the location this map location is for
* location - an numeric value to indicate which square to fill
* map_image
* place_id - the assigned place id (ie: a user's home)
* available - defines if the field is available for ownership


---------------


block maps were 12x6. block/present.tmpl appears to be the template for the block map.
intstead of a recursive function, it could be done with some sql innerjoins:
SELECT * FROM places as homes
INNER JOIN places as blocks
where blocks.id = homes.parent_place_id
INNER JOIN places as hoods
where hoods.id = blocks.parent_place_id
WHERE hoods.parent_place_id = {colony id}
hoods were 6x5
colonies were 8x5, and the map is located in community/preset.tmpl
That actually sounds like when a block/hood was created, so were a set number of Home records.
I'm starting to believe this was the case more and more as I read the reference, database structure and templates. When a hood or block was a created, it also populated records for the spaces on the map. Each record had a 2d map icon, some had a 'free' icon which would allow to be moved in. I guess they decided this if the 'Home' record had an owner or not.
We'll obviously need some way to configure the block/hood maps in the database. I just need to figure out the best way. Their's is one option, but maybe there is a better way.
again, just means testing my database structure. It all eventually affects how shared_objects are stored.
in bx community platform:

place I believe was for public spaces
home was for all levels of the "community" section (ie: colonies, hoods and blocks). It stored every level of this section here.
```

**Comment by dburleson** [comment]
Condensed Notes:

### Schema Changes

* add `place.type`

**New `map_location` table**

* parent_place_id - the id of the location this map location is for
* location - an numeric value to indicate which square to fill
* map_image
* place_id - the assigned place id (ie: a user's home)
* available - defines if the field is available for ownership



### Migration Steps

1) select the id of the X col
2) insert hoods into place 
3) get hood ids
4) insert into association table the ids of the above. relating them to the X col's id


### General Notes:

* hoods will have their own vue component, `place` record and an association record in the xref table to relate it to the parent colony.
* Hoods have chat
* Hoods don't have 3d chat

### Api Notes

* use endpoints such as `/hood/[id]`

**Comment by dburleson** [comment]
1. build db migration/seed of old data
2. build the hood level map page
3. link up the colonies to the correct hood ids.
4. move onto block level.
So, with hoods, we'll have empty hoods (no blocks) until the block level is built

**Comment by dburleson** [comment]
interesting note:

regarding places/homes/hoods/colonies/blocks:

"Unique ID of a district, neighborhood, block or home. The first 4 bytes distigu- ish districts, the next 4 bytes neighbor- hoods, etc (means up to 64k entities per level)"

[XXXX][XXXX][XXXX][XXXX]

[colony][hood][block][home]

**Comment by dburleson** [comment]
```sql
SELECT h.ID,h.Name, c.ID,c.Name
FROM neighborhood h
LEFT JOIN community c
ON substr(c.ID,1,4) = substr(h.ID,1,4)
```

associates the hoods to the colonies in old data.

**Comment by smile0711** [comment]
The message board coding right now only references places table.  If the hoods and blocks and homes are going to have their own table, then that is going to need to be manipulated to see where to look.

**Comment by troydotnz** [comment]
Cybertown and older versions of platform had their own tables however in later versions there is only a single places table. The schema between these is relatively constant and I couldn't see any reason to have different tables.

The ID Scheme that Platform used also necessitated changing the ID upon moving a home (as the ID was a unique key, it actually just copied the properties over). I would treat the ID as more of a "Physical Address" on the map for historical reference and use a different numerical unique ID.

**Comment by dburleson** [comment]
```sql
SELECT b.ID, 
b.Name, 
b.Index_Image, 
substr(b.ID,9,4) as block_map_coord,
n.ID, 
n.Name, 
substr(n.ID,5,4) as hood_map_coord,
c.ID, 
c.Name,
substr(c.ID,1,4) as colony_id
FROM block b
INNER JOIN neighborhood n
ON substr(n.ID,1,8) = substr(b.ID,1,8)
INNER JOIN community c
ON substr(c.ID,1,4) = substr(n.ID,1,4)
```

expanded query to get blocks, hoods and colony association, with IDs and positions.

**Comment by dburleson** [comment]
> The message board coding right now only references places table. If the hoods and blocks and homes are going to have their own table, then that is going to need to be manipulated to see where to look.

hoods and blocks will still have a record in `place` table, and thus an ID to associate all the message board data to.
