### ISSUE TITLE
Block Page Level

### ISSUE THREAD

**Issue by dburleson** [CybertownRevival/ctr#73]
Create a page to display the block level.

* [x] Clickable Map to visit homes(see archive repo)
* [ ] Message Board / Inbox
* [x] Map management (saved in the DB)

Issue to be expanded with supporting material (screenshots, templates, etc)

We feel there should be an JavaScript object which will hold theming details for the colony, hoods and blocks to reference for map images and icons.

Note: It was possible for home owners to choose their 2d map icon for their home.

**Comment by troydotnz** [comment]
Block Level Data

[block.sql.txt](https://github.com/CybertownRevival/ctr/files/8649961/block.sql.txt)
