### ISSUE TITLE
Colony Level User Tools

### ISSUE THREAD

**Issue by dburleson** [CybertownRevival/ctr#79]
Issue to be expanded with supporting material (screenshots, templates, etc)

Tools which allow Colony Leaders and Deputies to manage aspects of the colony.

**Comment by troydotnz** [comment]
If I could expand on this, Cybertown had a Rights/Roles system that applied hierarchically across all Places from the Community Level down. Homes & Clubs had somewhat similar roles.

You could define what roles were assigned to the Owner and have up to 8 Writers/Readers with varying capabilities. Assigning people to these basically gave them a "job". There's alot of documentation on how this works in the platform documentation.

I wouldn't suggest emulating this limited system verbatim but I do think having a basic RBAC you can apply to any place would make things more dynamic.
