### ISSUE TITLE
Inbox

### ISSUE THREAD

**Issue by dburleson** [CybertownRevival/ctr#83]
Many areas of CT has a private inbox with customisation options for those with the correct rights access.

The inbox allowed others to send a private 'email like' message to individuals.

CT allowed unrestricted HTML input. However, for security reasons, we will need to restrict these to JUST HTML. No Scripts of any sort will be allowed. Validation and cleaning of user input must happen on the backend.

**Comment by XDKRGL** [comment]
when you can , you can mark this issue resolved :P
